spring:
  application:
    name: webshell
  main:
    banner-mode: "off"
server:
  port: ${PORT:8001}
userpassword: "{bcrypt}$2a$10$dmExX9/1Xjw.uJEXFpA1SOORnDrxY3jrQUPf3LH32qHIHbIlz28ZG"
testpassword: "{bcrypt}$2a$10$jVMqtVkvsA7RMHiBP1itvOh2022sBvv4NitloY.WESdcnVWOZ3U4y"
